# Generated by Django 6.0.2 on 2026-03-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Logical name, e.g. web-01', max_length=128, unique=True)),
                ('hostname_hint', models.CharField(blank=True, help_text='Optional note; agent reports actual hostname in payloads.', max_length=255)),
                ('api_token_hash', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_hostname', models.CharField(max_length=255)),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingests', to='metrics.monitoredhost')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['host', '-collected_at'], name='metrics_met_host_id_392a17_idx')],
            },
        ),
    ]
